import React, { useEffect, useState } from 'react';
import "./Home.css";
import { Card, FormField, Loader } from '../components';
import child from "./images/child.jpeg";
import file1 from "./images/file1.jpeg";
import file2 from "./images/file2.jpeg";
import google from "./images/google.jpeg";
import painting from "./images/painting.jpeg";
import robot from "./images/robot.jpeg";

const RenderCards = ({ data, title }) => {
  if (data?.length > 0) {
    return (
      data.map((post) => <Card key={post._id} {...post} />)
    );
  }

  return (
    <h2 className="mt-5 font-bold text-[#6469ff] text-xl uppercase">{title}</h2>
  );
};

const Home = () => {
  const [loading, setLoading] = useState(false);
  const [allPosts, setAllPosts] = useState(null);

  const [searchText, setSearchText] = useState('');
  const [searchTimeout, setSearchTimeout] = useState(null);
  const [searchedResults, setSearchedResults] = useState(null);
  // const temp = [
  //   {
  //     'name': 'dharneesh',
  //     'branch': 'IT',
  //     'section': 'A'
  //   }
  // ]


    const temp1 = [
        {
          id: 1,
          image : google,
          "prompt" : "Sample Text"
        },
        {
          id: 1,
          image : child,
          "prompt" : "Sample Text"
        },
        {
          id: 1,
          image : painting,
          "prompt" : "Sample Text"
        }
      ]

    const temp2 = [
        {
          id: 1,
          image : file1,
          "prompt" : "Sample Text"
        },
        {
          id: 1,
          image : file2,
          "prompt" : "Sample Text"
        },
        {
          id: 1,
          image : robot,
          "prompt" : "Sample Text"
        }
    ]

  const fetchPosts = async () => {
   
    setLoading(true);

    try {
      const response = await fetch('https://dalle-arbb.onrender.com/api/v1/post', {
        method: 'GET',
        headers: {
          'Content-Type': 'application/json',
        },
      });

      if (response.ok) {
        const result = await response.json();
        setAllPosts(result.data.reverse());
      }
    } catch (err) {
      alert(err);
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    fetchPosts();
  }, []);

  const handleSearchChange = (e) => {
    clearTimeout(searchTimeout);
    setSearchText(e.target.value);

    setSearchTimeout(
      setTimeout(() => {
        const searchResult = allPosts.filter((item) => item.name.toLowerCase().includes(searchText.toLowerCase()) || item.prompt.toLowerCase().includes(searchText.toLowerCase()));
        setSearchedResults(searchResult);
      }, 500),
    );
  };

  return (
    <section className="max-w-7xl mx-auto">
      <div>
        <h1 className="font-extrabold text-[#222328] text-[32px]">The Community Showcase</h1>
        <p className="mt-2 text-[#666e75] text-[14px] max-w-[500px]">Browse through a collection of imaginative and visually stunning images generated by Dharaneesh's AI</p>
      </div>

      {/* <div className="mt-16">
        <FormField
          labelName="Search posts"
          type="text"
          name="text"
          placeholder="Search something..."
          value={searchText}
          handleChange={handleSearchChange}
        />
      </div> */}
{/* 
      {temp1.map((each, index) => 
        <div className = "Main" key={index}><div className = "Card" ><img src = {each.image} alt = "alternate" />  
        <h3>{each.prompt}</h3>   </div>  </div>
      )}
      {temp2.map((each, index) => 
        <div className = "Main" key={index}><div className = "Card" ><img src = {each.image} alt = "alternate" />  
        <h3>{each.prompt}</h3>   </div>  </div>
      )} */}
      <div className='instructions'>
        <h1><b> <i>Instructions</i></b></h1>
        <p><b>Step : 1</b> Click on <b>create</b> button</p>
        <p><b>Step : 2</b> Fill the details below </p>
        <p><b>Step : 3</b> Give a proper Scenario for better picture</p>
        <p><b>Step : 4</b> Click on <b>Generate</b> for picture,if you didnt like picture the re click <b>generate</b></p>
        <p><b>Step : 5</b> To share with Community click the blue Button</p>
      </div>
      <div className='Main'>
        <div className='Card'>
          <img src = {google} alt = "" />
          <h3>Sample Text</h3>
        </div>
        <div className='Card'>
          <img src = {file1} alt = "" />
          <h3>Sample Text</h3>
        </div>
        <div className='Card'>
          <img src = {file2} alt = "" />
          <h3>Sample Text</h3>
        </div>
      </div>
      <div className='Main'>
        <div className='Card'>
          <img src = {painting} alt = "" />
          <h3>Sample Text</h3>
        </div>
        <div className='Card'>
          <img src = {robot} alt = "" />
          <h3>Sample Text</h3>
        </div>
        <div className='Card'>
          <img src = {child} alt = "" />
          <h3>Sample Text</h3>
        </div>
      </div>
      
      {/* <div className="mt-10">
        {loading ? (
          <div className="flex justify-center items-center">
            <Loader />
          </div>
        ) : (
          <>
            {searchText && (
              <h2 className="font-medium text-[#666e75] text-xl mb-3">
                Showing Resuls for <span className="text-[#222328]">{searchText}</span>:
              </h2>
            )}
            <div className="grid lg:grid-cols-4 sm:grid-cols-3 xs:grid-cols-2 grid-cols-1 gap-3">
              {searchText ? (
                <RenderCards
                  data={searchedResults}
                  title="No Search Results Found"
                />
              ) : (
                <RenderCards
                  data={allPosts}
                  title="No Posts Yet"
                />
              )}
            </div>
          </>
        )}
      </div> */}
    </section>
  );
};

export default Home;